export const CIRCUIT_MESH_MAP = {
    "yas-marina": "mesh",
    "melbourne": "mesh001",
    "speilberg": "mesh002",
    "baku": "mesh003",
    "sakhir": "mesh004",
    "spa-francorchamps": "mesh005",
    "sao-paulo": "mesh006",
    "montreal": "mesh007",
    "shanghai": "mesh008",
    "imola": "mesh009",
    "silverstone": "mesh010",
    "mogyorod": "mesh011",
    "monza": "mesh012",
    "suzuka": "mesh013",
    "las-vegas": "mesh014",
    "mexico-city": "mesh015",
    "miami": "mesh016",
    "monaco": "mesh017",
    "lusail": "mesh019",
    "jeddah": "mesh020",
    "singapore": "mesh021",
    "barcelona": "mesh022",
    "austin": "mesh023",
    "zandvoort": "mesh024",
};

export const CIRCUIT_COUNTRY = {
    "yas-marina": "ABU DABI",
    "melbourne": "AUSTRALIA",
    "speilberg": "AUSTRIA",
    "baku": "AZERBAIJAN",
    "sakhir": "BAHREIN",
    "spa-francorchamps": "BÉLGICA",
    "sao-paulo": "BRASIL",
    "montreal": "CANADÁ",
    "shanghai": "CHINA",
    "imola": "ITALIA",
    "silverstone": "REINO UNIDO",
    "mogyorod": "HUNGRÍA",
    "monza": "ITALIA",
    "suzuka": "JAPÓN",
    "las-vegas": "LAS VEGAS",
    "mexico-city": "MÉXICO",
    "miami": "MIAMI",
    "monaco": "MÓNACO",
    "lusail": "QATAR",
    "jeddah": "ARABIA SAUDITA",
    "singapore": "SINGAPUR",
    "barcelona": "ESPAÑA",
    "austin": "ESTADOS UNIDOS",
    "zandvoort": "PAÍSES BAJOS",
};

export const CIRCUIT_ORDER = [
    "yas-marina", "lusail", "las-vegas", "sao-paulo", "mexico-city", "austin",
    "singapore", "baku", "monza", "zandvoort", "mogyorod", "spa-francorchamps",
    "speilberg", "montreal", "barcelona", "imola", "melbourne", "shanghai",
    "suzuka", "sakhir", "jeddah", "miami", "monaco", "silverstone"
];

export const CIRCUIT_INDEX_MAP = {
    "sakhir": 0,
    "jeddah": 1,
    "melbourne": 2,
    "suzuka": 3,
    "shanghai": 4,
    "miami": 5,
    "imola": 6,
    "monaco": 7,
    "montreal": 8,
    "barcelona": 9,
    "speilberg": 10,
    "silverstone": 11,
    "mogyorod": 12,
    "spa-francorchamps": 13,
    "zandvoort": 14,
    "monza": 15,
    "baku": 16,
    "singapore": 17,
    "austin": 18,
    "mexico-city": 19,
    "sao-paulo": 20,
    "las-vegas": 21,
    "lusail": 22,
    "yas-marina": 23
};
